# Generated by Django 5.1 on 2024-08-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('dateCreate', models.DateField(auto_now=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=100)),
            ],
        ),
    ]
